spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path=matcher
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  flyway:
    locations:
      - db.migration